service: serverless-starter
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 20
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  tracing:
    lambda: true
  environment:
    BINARY_CONTENT_TYPES: application/json,image/png

package:
  patterns:
    - '!.idea/**'
    - '!src/**'
    - '!client/**'
    - 'client/build/**'
    - 'dist/**'

functions:
  app:
    handler: dist/serverless.app
    events:
      - httpApi: '*'
